import type { EnemyConfig, EnemyType } from '@game/types';

export const ENEMIES: Record<EnemyType, EnemyConfig> = {
  basic: {
    hp: 1,
    speed: 110,
    scoreValue: 100,
    width: 18,
    height: 18,
    color: 0xcc3333,
    movement: 'linear',
    fireRate: 0,
    damage: 1,
  },
  shooter: {
    hp: 2,
    speed: 75,
    scoreValue: 200,
    width: 20,
    height: 20,
    color: 0xcc8833,
    movement: 'sinusoidal',
    fireRate: 1.4,
    damage: 1,
  },
  kamikaze: {
    hp: 1,
    speed: 200,
    scoreValue: 200,
    width: 14,
    height: 14,
    color: 0xff4488,
    movement: 'homing',
    fireRate: 0,
    damage: 2,
  },
  tank: {
    hp: 5,
    speed: 45,
    scoreValue: 400,
    width: 28,
    height: 28,
    color: 0x666699,
    movement: 'linear',
    fireRate: 0.9,
    damage: 1,
  },
  elite: {
    hp: 3,
    speed: 95,
    scoreValue: 500,
    width: 22,
    height: 22,
    color: 0xaa44cc,
    movement: 'zigzag',
    fireRate: 0.7,
    damage: 1,
  },
  splitter: {
    hp: 2,
    speed: 90,
    scoreValue: 250,
    width: 20,
    height: 20,
    color: 0x44cc88,
    movement: 'linear',
    fireRate: 0,
    damage: 1,
    splitInto: 'basic',
    splitCount: 2,
  },
  sniper: {
    hp: 2,
    speed: 60,
    scoreValue: 300,
    width: 16,
    height: 22,
    color: 0x33aacc,
    movement: 'hover',
    fireRate: 2.0,
    damage: 1,
  },
  miniboss: {
    hp: 8,
    speed: 35,
    scoreValue: 800,
    width: 26,
    height: 26,
    color: 0xdd6622,
    movement: 'sinusoidal',
    fireRate: 0.6,
    damage: 1,
    guaranteedDrop: true,
  },
};
